project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

website:
  title: "blockr"
  page-navigation: true
  page-footer:
    left: |
      Proudly supported by
      [![](/logos/logo-bms.png){fig-alt="Bristol Myers Squibb" width=135px}](https://www.bms.com/)
    center:
      - text: "Build analyses in minutes, click by click."
    right:
      - icon: github
        href: https://github.com/BristolMyersSquibb/blockr
        aria-label: Blockr GitHub
  navbar:
    title: false
    logo: /logos/logo-blockr.png
    logo-alt: "Blockr logo."
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/BristolMyersSquibb/blockr
          - text: Report a Bug
            href: https://github.com/BristolMyersSquibb/blockr/issues
    left:
      - text: "Tutorials"
        href: tutorials/00-getting-started.qmd
      - text: "How-To"
        href: howto/index.qmd
      - text: "Fundamentals"
        href: fundamentals/index.qmd
      - text: "Reference"
        href: reference/index.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: "light"
      contents:
        - tutorials/00-getting-started.qmd
        - tutorials/01-build-your-first-app.qmd
        - tutorials/02-build-a-dashboard.qmd
        - tutorials/03-youtube-series.qmd
    - title: "How-To"
      contents:
        - howto/index.qmd
    - title: "Fundamentals"
      contents:
        - fundamentals/index.qmd
    - title: "Reference"
      contents:
        - reference/index.qmd