project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

website:
  title: "blockr"
  navbar:
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/BristolMyersSquibb/blockr
          - text: Report a Bug
            href: https://github.com/BristolMyersSquibb/blockr/issues
    left:
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "How-To"
        href: howto/index.qmd
      - text: "Fundamentals"
        href: fundamentals/index.qmd
      - text: "Reference"
        href: reference/index.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: "light"
      contents:
        - tutorials/index.qmd
        - tutorials/*.qmd 

    - title: "How-To"
      contents:
        - howto/*.qmd

    - title: "Fundamentals"
      contents:
        - fundamentals/*.qmd

    - title: "Reference"
      contents:
        - reference/*.qmd
